ui: tape
concurrency: 1
browsers:
  - name: chrome
    version: latest
  - name: firefox
    version: latest
  - name: microsoftedge
    version: [13, latest]
  - name: safari
    version: latest
  - name: iphone
    version: [9, latest]
  - name: android
    version: latest
