steps:
  - name: ':docker: :package: tests node8'
    plugins:
      'docker-compose#v1.7.0':
        build: browser-tests-node-last
        config: docker-compose-node-last.yml
        image-repository: 027047743804.dkr.ecr.us-east-2.amazonaws.com/uber
    agents:
      queue: builders
  - wait
  - name: ':saucelabs: :selenium: node8'
    command: .buildkite/run-all-tests.sh
    concurrency: 1
    concurrency_group: saucelabs
    plugins:
      'docker-compose#v1.7.0':
        run: browser-tests-node-last
        config: docker-compose-node-last.yml
    agents:
      queue: workers
