steps:
  - name: ':docker: :package: tests'
    plugins:
      'rtsao/docker-compose#e47c1ae':
        build:
          - browser-tests
          - fusion-server
          - sauce-tunnel-healthy
          - fusion-server-healthy
        image-repository: 027047743804.dkr.ecr.us-east-2.amazonaws.com/uber
    agents:
      queue: builders
  - name: ':docker: :package: linters'
    plugins:
      'rtsao/docker-compose#e47c1ae':
        build: browser-tests-linters
        image-repository: 027047743804.dkr.ecr.us-east-2.amazonaws.com/uber
    agents:
      queue: builders
  - wait
  - command: yarn flow
    name: ':flowtype:'
    plugins:
      'rtsao/docker-compose#e47c1ae':
        run: browser-tests-linters
    agents:
      queue: workers
  - name: ':eslint:'
    command: yarn lint
    plugins:
      'rtsao/docker-compose#e47c1ae':
        run: browser-tests-linters
    agents:
      queue: workers
  - name: ':saucelabs: :selenium: :safari: 9'
    command: ./test-remotely.sh safari-9
    concurrency: 5
    concurrency_group: saucelabs
    plugins:
      'rtsao/docker-compose#e47c1ae':
        run: browser-tests
        pull:
          - fusion-server
          - sauce-tunnel-healthy
          - fusion-server-healthy
    agents:
      queue: workers
  - name: ':saucelabs: :selenium: :safari: 11'
    command: ./test-remotely.sh safari-11
    concurrency: 5
    concurrency_group: saucelabs
    plugins:
      'rtsao/docker-compose#e47c1ae':
        run: browser-tests
        pull:
          - fusion-server
          - sauce-tunnel-healthy
          - fusion-server-healthy
    agents:
      queue: workers
  - name: ':saucelabs: :selenium: :safari: 12'
    command: ./test-remotely.sh safari-12
    concurrency: 5
    concurrency_group: saucelabs
    plugins:
      'rtsao/docker-compose#e47c1ae':
        run: browser-tests
        pull:
          - fusion-server
          - sauce-tunnel-healthy
          - fusion-server-healthy
    agents:
      queue: workers
  - name: ':saucelabs: :selenium: :ie: 9'
    command: ./test-remotely.sh ie-9
    concurrency: 5
    concurrency_group: saucelabs
    plugins:
      'rtsao/docker-compose#e47c1ae':
        run: browser-tests
        pull:
          - fusion-server
          - sauce-tunnel-healthy
          - fusion-server-healthy
    agents:
      queue: workers
  - name: ':saucelabs: :selenium: :ie: 11'
    command: ./test-remotely.sh ie-11
    concurrency: 5
    concurrency_group: saucelabs
    plugins:
      'rtsao/docker-compose#e47c1ae':
        run: browser-tests
        pull:
          - fusion-server
          - sauce-tunnel-healthy
          - fusion-server-healthy
    agents:
      queue: workers
  - name: ':saucelabs: :selenium: :edge:'
    command: ./test-remotely.sh edge
    concurrency: 5
    concurrency_group: saucelabs
    plugins:
      'rtsao/docker-compose#e47c1ae':
        run: browser-tests
        pull:
          - fusion-server
          - sauce-tunnel-healthy
          - fusion-server-healthy
    agents:
      queue: workers
  - name: ':saucelabs: :selenium: :android: Samsung S3'
    command: ./test-remotely.sh samsung-S3
    concurrency: 5
    concurrency_group: saucelabs
    plugins:
      'rtsao/docker-compose#e47c1ae':
        run: browser-tests
        pull:
          - fusion-server
          - sauce-tunnel-healthy
          - fusion-server-healthy
    agents:
      queue: workers
  - name: ':saucelabs: :selenium: :android: Samsung G4'
    command: ./test-remotely.sh samsung-G4
    concurrency: 5
    concurrency_group: saucelabs
    plugins:
      'rtsao/docker-compose#e47c1ae':
        run: browser-tests
        pull:
          - fusion-server
          - sauce-tunnel-healthy
          - fusion-server-healthy
    agents:
      queue: workers
  - name: ':saucelabs: :selenium: :iphone: 5S'
    command: ./test-remotely.sh iPhone-5s
    concurrency: 5
    concurrency_group: saucelabs
    plugins:
      'rtsao/docker-compose#e47c1ae':
        run: browser-tests
        pull:
          - fusion-server
          - sauce-tunnel-healthy
          - fusion-server-healthy
    agents:
      queue: workers
  - name: ':saucelabs: :selenium: Kindle Fire'
    command: ./test-remotely.sh kindleFire
    concurrency: 5
    concurrency_group: saucelabs
    plugins:
      'rtsao/docker-compose#e47c1ae':
        run: browser-tests
        pull:
          - fusion-server
          - sauce-tunnel-healthy
          - fusion-server-healthy
    agents:
      queue: workers
