#!/usr/bin/env bash

set -x

# run in series due to saucelabs concurrency limits
nightwatch --config nightwatch-ci.js --env chrome-mac
nightwatch --config nightwatch-ci.js --env chrome-windows
nightwatch --config nightwatch-ci.js --env safari-7
nightwatch --config nightwatch-ci.js --env safari-9
nightwatch --config nightwatch-ci.js --env safari-11
nightwatch --config nightwatch-ci.js --env ie-9
# nightwatch --config nightwatch-ci.js --env ie-11 ("Promise is not defined")
nightwatch --config nightwatch-ci.js --env edge
# nightwatch --config nightwatch-ci.js --env samsung-S3 ("Error processing the server response")
# nightwatch --config nightwatch-ci.js --env samsung-G4 ("Map is not defined")
nightwatch --config nightwatch-ci.js --env iPhone-4S
nightwatch --config nightwatch-ci.js --env iPhone-X
# nightwatch --config nightwatch-ci.js --env kindleFire ("Map is not defined")
